name: TestGithub1
version: 0.0.1
author: Mr Personne <mypersonner@xxx.com>
description: Some descript
homepage: https://github.com/trippolo/TestGitHub1
documentation: 
dependencies:
  unittest: any
  browser: any
